# Inherit from your local RuboCop configuration file
inherit_from:
  - https://raw.githubusercontent.com/nanafox/rubocop-config/refs/heads/main/.rubocop.yml

# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Exclude:
    - 'config/**/*'
    - Gemfile
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/Documentation:
  Exclude:
    - db/**/*

Metrics/AbcSize:
  Exclude:
    - 'db/**/*'
